import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import "../../components/type-scale.css";
import "../../components/hero/styles.css";
import "../../components/feed/styles.css";
import "../../components/steam-data/styles.css";
import "../../components/vertical-video/styles.css";
import "../../components/page-content/styles.css";
import "../../components/image-gallery/styles.css";
import "../../components/timeline/styles.css";
import "../../components/game-review/styles.css";
import "../../components/key-info/styles.css";
import "../../components/inline-poll/styles.css";
import "../../components/rankings-table/styles.css";
import "../../components/contribution-tracker/styles.css";
import "../../components/featured-article/styles.css";
import "../../components/stance/styles.css";
import "../../components/countdown/styles.css";
import "../../components/editor-highlight/styles.css";
import App from "./App";

createRoot(document.querySelector("#root")!).render(<StrictMode><App /></StrictMode>);
